name: Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Kết nối ssh linux -> và pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /var/www/furniture_shop/server
            git pull
            curl -X POST -H 'Content-Type: application/json' -H 'Authorization: ${{ secrets.DC_KEY_BOT }}' -d '{"content":"Deploy server success at https://server1.kansan.io.vn"}' https://discord.com/api/v9/channels/1193076191905718392/messages

    # curl -X POST -H 'Content-Type: application/json' -H 'Authorization: ${{ secrets.DC_KEY }}' -d '{"content":"Deploy success at https://furniture.kansan.io.vn"}' https://discord.com/api/v9/channels/1189872165470871632/messages
